### PR TITLE
Fix compiling on Linux, revisit project structure

### PR DESCRIPTION
**Pull request by CodeFinder2**
Thanks for the library and for taking a look at my PR! :-)

### CODE REVIEW

**Comment by ilyanikolaevsky** [comment]
Thanks for the change. 
However, I'm against the new project structure. 
I'm more fond of headers and cpp files staying together.

Could you please revert the changes around "include" directory? I'll approve everything else gladly.

**Comment by ilyanikolaevsky** [comment]
Also, please update the readme.md file (the section describing the code structure).

**Comment by CodeFinder2** [comment]
I've reverted my last commit containing the structural changes. There's then no need for updating the README. (If there is still and I am missing something, please let me know!) ;-)

However, you should really take a look at modern C++/CMake projects and their structure and consider moving to that new structure since the current version is very "custom". See e.g., https://github.com/TheLartians/ModernCppStarter

Nonetheless, thanks for taking a look and merging the rest! :-)

**Comment by ilyanikolaevsky** [comment]
Thanks for the PR, once again!

**Pull request merged**
